version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: corrigeai_backend
    ports:
      - "3000:3000" 
      - "9229:9229"
    environment:
      DB_HOST: aws-0-sa-east-1.pooler.supabase.com
      DB_PORT: 6543
      DB_USERNAME: postgres.jnhloivnxpzufklhifek
      DB_PASSWORD: 2!axK2UVfx#3@LK
      DB_NAME: postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev
